= klanglicht-kt
:doctype: book
:description: Documentation for klanglicht-kt
:keywords: kotlin, dmx, serial-usb
:icons: font
:toc:
:toc-title: Inhalt
:toclevels: 10

== Status

https://github.com/sknull/klanglicht-kt/actions/workflows/github-ci.yml[image:https://github.com/sknull/klanglicht-kt/actions/workflows/github-ci.yml/badge.svg[Klanglicht Kt]]

== History

This project started as a simple proof of concept if it would be possible to get some simple RGB light working
using a DMX interface.

After researching about possible interfaces I decided for the Eurolite DMX Pro 512 for which I was able to find some information about it's link:/resources/hardware/Eurolite_USB-DMX512-PRO_serial-protocol_discussion-thread.pdf[serial protocol].

After playing around a bit a first prototype was implemented which was able to fade in a color from black and vice versa (wow!).

A printout of the thread with those golden informations which kick started me once back and the original hardware manual are attached to this project

* link:docs/hardware/eurolite/Eurolite_USB-DMX512-PRO_serial-protocol_discussion-thread.pdf[Discussion Thread (German)]
* link:docs/hardware/eurolite/Eurolite_USB-DMX512_PRO_manual_german.pdf[Manual (German)]

As the lightmanager is an abandoned piece of hardware now I started to get rid of the most functionality.
All sequences formerly handled by the lightmanager are now controlled by the klanglicht server.
This is also true for all shelly, dmx and video receiver operations (such as sound programs, etc.).
State is handled within the lightmaneger so I could also get rid of all the markers formerly used in the
lightmanager.
Finally the lightmanager now acts only as an interface between my harmony remote and the klanglicht server.

Hardware handlers implemented so far in this project:

- Shelly devices
- DMX devices
- Lightmanager Air scenes
- Sound programs of my Yamaha receiver
- Twinkly devices (developed in a link:https://github.com/sknull/twinkly-kt[side project]) also in kotlin - still work in progress

The only things not controllable directly is the one Idual back light and the Grundig stripes. For the latter I teached the IR codes into the lightmanager.

Currently I am working on integrating the twinkly devices in my setup. So far i am able to control single led's in those devices and can show images and slide shows. So those could be used later as decorative elements.

== My Equipment

=== HiFi

- video receiver Yamaha RX-V6A
- 7.1.2 loudspeaker system
* front, center and surround: Magnat Monitor Supreme series
* upper surround for Atmos: Yamaha
- 4k bluray player (Sony)
- Technics CD Player (still running after 30 years in operation)

=== TV

- 75" flat screen by LG
- Telekom Magenta Tv stick
- Amazon Fire TV (now used as the main player device with a sideloaded Kodi which is configured to access my media library on the NAS)

=== Remote Controls

- Harmony Elite universal remote with a hub
- Lightmanager Air as the central control of all this

=== NAS

- Qnap TS-233 NAS with 2 x 10TB hard discs

=== Lighting

- Some DMX fixtures
- Some RGB Led Stripes controlled by shelly RGBW devices
- Two Grundig RGB lightstrips which are controlled via IR
- Some lighting in my home is also controlled by shelly devices
- An Idual RGB light used as the default back light of my TV set
- Four twinkly curtain and one twinkly matrix

=== Server

- Raspberry pi 3b with the eurolite DMX interface attached running the klanglicht application
