spring:
  profiles:
    active: local
  config:
    import: file:${user.home}/.klanglicht/resources/application.yml

management:
  endpoint:
    shutdown:
      enabled: true
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "health,shutdown"

application:
  klanglichtDirectory: file:${user.home}/.klanglicht
